---
- hosts: kafka_zookeeper
  become: yes
  tasks:
  - name: Install package
    apt:
      name: zookeeper
      state: present

  - name: Start and enable kafka zookeeper service
    ansible.builtin.service:
      name: zookeeper
      state: started
      enabled: yes
    become: yes
