{{- if eq .Values.core.apiVersion "v1beta2" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{- include "instana-core.fullname" . | nindent 4 }}
  labels:
    {{- include "instana-core.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    adminPassword: {{ .Values.secret.adminPassword }}
    dhParams: |
      {{- .Values.secret.dhParams | nindent 6 }}
    downloadKey: {{ .Values.secret.downloadKey }}
    salesKey: {{ .Values.secret.salesKey }}
    tokenSecret: {{ .Values.secret.tokenSecret }}
    rawSpansStorageConfig:
      {{- with .Values.secret.rawSpansStorageConfig.s3Config }}
      {{- if and .accessKeyId .secretAccessKey }}
      s3Config:
        accessKeyId: {{ .accessKeyId | nindent 8 }}
        secretAccessKey: {{ .secretAccessKey | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.secret.rawSpansStorageConfig.gcloudConfig.serviceAccountKey }}
      gcloudConfig:
        serviceAccountKey: |
          {{ . | nindent 10 }}
        {{- end }}
    serviceProviderConfig:
      keyPassword: {{ .Values.secret.serviceProviderConfig.keyPassword }}
      pem: |
        {{- .Values.secret.serviceProviderConfig.pem | nindent 8 }}
type: Opaque

{{- end }}
