{{- if or (eq .Values.core.apiVersion "v1beta1") .Values.legacy.keep }}

apiVersion: v1
kind: Secret
metadata:
  name: instana-base
  labels:
    {{- include "instana-core.labels" . | nindent 4 }}
stringData:
  adminPassword: {{ .Values.secret.adminPassword }}
  dhparams.pem: |
    {{- .Values.secret.dhParams | nindent 4 }}
  downloadKey: {{ .Values.secret.downloadKey }}
  license: {{ .Values.secret.license }}
  salesKey: {{ .Values.secret.salesKey }}
  token.secret: {{ .Values.secret.tokenSecret }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: instana-service-provider
  labels:
    {{- include "instana-core.labels" . | nindent 4 }}
stringData:
  sp.pem: |
    {{- .Values.secret.serviceProviderConfig.pem | nindent 4 }}
  sp.key.pass: {{ .Values.secret.serviceProviderConfig.keyPassword }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: instana-spans
  labels:
    {{- include "instana-core.labels" . | nindent 4 }}
stringData:
  accessKeyId: {{ .Values.legacy.rawSpansStorageConfig.objectStorageConfig.accessKeyId }}
  secretAccessKey: {{ .Values.legacy.rawSpansStorageConfig.objectStorageConfig.secretAccessKey }}
type: Opaque

{{- end }}
