{{- if eq .Values.unit.apiVersion "v1beta2" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{- include "instana-unit.fullname" . | nindent 4 }}
  labels:
    {{- include "instana-unit.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    license: {{ .Values.secret.license }}
    agentKeys:
    {{- range .Values.secret.agentKeys }}
      - {{ . }}
    {{- end }}
type: Opaque

{{- end }}
