packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.1"
      source = "github.com/hashicorp/amazon"
    }
  }
}

source "amazon-ebs" "autogenerated_1" {
  ami_name                    = format("instana/images/fleet/hvm/base-bionic-%s", formatdate("YYYYMMDDHHmmss", timestamp()))
  ami_users                   = ["305565433046"]
  associate_public_ip_address = false
  ena_support                 = true
  instance_type               = "m3.medium"
  region                      = "${var.region}"
  security_group_id           = "${var.security_group}"
  source_ami                  = "${var.source_ami}"
  ssh_interface               = "private_ip"
  ssh_keypair_name            = "instanacd-new"
  ssh_private_key_file        = "${var.ssh_location}"
  ssh_username                = "ubuntu"
  subnet_id                   = "${var.subnet}"
  tags = {
    Name            = "PackerBuildFleet"
    distro          = "bionic"
    "instana:image" = "base"
    purpose         = "${var.purpose}"
  }
  vpc_id = "${var.vpc}"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/provision.sh"
    source      = "./provision.sh"
  }

  provisioner "file" {
    destination = "/tmp/secrets.yml"
    source      = "${var.secrets_path}"
  }

  provisioner "shell" {
    # See cookbook instana-base-common::default forr PACKER_BUILD_NAME
    inline = ["sudo chmod 777 /tmp/provision.sh", "sudo PACKER_BUILD_NAME=fleet_amis /tmp/provision.sh base-ec2 ${var.region}"]
  }
}
